name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_versions.txt
          pip install ruff pytest
      - name: Run Ruff
        run: ruff check .
      - name: Run Pytest
        run: pytest
